#!/usr/bin/env python3
"""Write the root Cargo.toml from the upstream librustzcash workspace manifest.

Usage: generate-workspace.py <repo-root>

The root manifest is generated output, not a hand-maintained file. Upstream
owns the dependency versions the vendored crates share, and generating rather
than merging this file is what keeps the Zakura rewiring out of every upstream
merge: the rules live in manifests/sources.toml, and the manifest they are
applied to arrives untouched on the vendor branch.

Five rules are applied to `[workspace.dependencies]`:

1. a dependency named in the manifest's `[rewire]` table is redirected at the
   configured Zakura fork and immutable revision, keeping the upstream key so
   crate sources are unchanged (`orchard = { package = "zakura-orchard", ... }`);
2. a path dependency on a crate this repository vendors keeps its path,
   rewritten into the vendored directory, gains the crate's published name,
   and takes the Zakura `version` from `[[crate]]` rather than upstream's;
3. any other path dependency loses its path and becomes a plain crates.io
   requirement, because `libraries` resolves those same crates from crates.io
   and a second local copy would be a distinct type.
4. a dependency named in `[versions]` keeps its upstream metadata but takes the
   configured version required by the selected Zakura release family;
5. a dependency listed in `[unused].dependencies` is omitted.

The manifest's `[patch]` tables are written verbatim as the workspace's
`[patch]` tables.

`workspace.package.repository` is rewritten to this repository so published
crates do not advertise the upstream librustzcash URL, and
`workspace.package.rust-version` is set to the Zakura release family's MSRV.
"""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

MEMBER_BLOCK = re.compile(r"^members = \[\n.*?^\]\n", re.MULTILINE | re.DOTALL)
# One `key = { ... }` or `key = "..."` line inside [workspace.dependencies].
DEPENDENCY = re.compile(
    r'^(?P<key>[A-Za-z0-9_-]+) = (?P<value>\{[^\n]*\}|"[^"]*")$', re.MULTILINE
)

BANNER = """# Generated by scripts/sync-upstream.sh from the upstream librustzcash
# workspace manifest. Do not edit: change manifests/sources.toml instead and
# re-run the sync, or the next upstream release will discard the edit.
#
# Members are the wallet-layer crates this repository forks, plus the
# hand-written members listed in that manifest. The crypto stack
# they depend on is resolved from the published zakura-* crates, and every
# other librustzcash component from its crates.io release, so exactly one copy
# of each package can ever enter a consumer's graph.
"""


def parse_inline_table(value: str) -> dict[str, str]:
    """Split an inline table into ordered `key -> raw TOML value` pairs."""
    if value.startswith('"'):
        return {"version": value}

    fields: dict[str, str] = {}
    for field in re.findall(r'([A-Za-z0-9_-]+) = ("(?:[^"]*)"|\[[^\]]*\]|[^,}]+)', value):
        fields[field[0]] = field[1].strip()
    return fields


def render(fields: dict[str, str]) -> str:
    return "{ " + ", ".join(f"{key} = {value}" for key, value in fields.items()) + " }"


def render_patches(patches: dict[str, dict[str, dict[str, str]]]) -> str:
    """Render the manifest's `[patch.<registry>]` tables as TOML."""
    sections = []
    for registry, entries in patches.items():
        lines = [f"[patch.{registry}]"]
        for name, source in entries.items():
            fields = {key: f'"{value}"' for key, value in source.items()}
            lines.append(f"{name} = {render(fields)}")
        sections.append("\n".join(lines) + "\n")
    return "\n".join(sections)


def main(argv: list[str]) -> int:
    if len(argv) != 2:
        print(__doc__.strip(), file=sys.stderr)
        return 2

    repo_root = Path(argv[1])

    with (repo_root / "manifests" / "sources.toml").open("rb") as manifest_file:
        manifest = tomllib.load(manifest_file)

    upstream_manifest = repo_root / manifest["layout"]["upstream_manifest"]

    vendored = {crate["path"]: crate for crate in manifest["crate"]}
    for crate in vendored.values():
        if "version" not in crate:
            print(
                f"crate {crate.get('package', crate['path'])} is missing version",
                file=sys.stderr,
            )
            return 1

    rewire = manifest["rewire"]
    versions = manifest.get("versions", {})
    unused = set(manifest.get("unused", {}).get("dependencies", []))
    layout = manifest["layout"]
    vendored_directory = layout["vendored_directory"]

    text = upstream_manifest.read_text()

    repository = layout.get("repository")
    if repository:
        text, replaced = re.subn(
            r'^repository = "https://github.com/zcash/librustzcash"$',
            f'repository = "{repository}"',
            text,
            count=1,
            flags=re.MULTILINE,
        )
        if replaced != 1:
            print("could not rewrite workspace.package.repository", file=sys.stderr)
            return 1

    rust_version = layout.get("rust_version")
    if rust_version:
        text, replaced = re.subn(
            r'^rust-version = "[^"]+"$',
            f'rust-version = "{rust_version}"',
            text,
            count=1,
            flags=re.MULTILINE,
        )
        if replaced != 1:
            print("could not rewrite workspace.package.rust-version", file=sys.stderr)
            return 1

    members = "".join(
        f'    "{vendored_directory}/{path}",\n' for path in vendored
    )
    # Hand-written members are appended, never generated: sync does not own
    # them, and they must survive an upstream release untouched.
    members += "".join(f'    "{member}",\n' for member in layout["extra_members"])
    text, count = MEMBER_BLOCK.subn(f"members = [\n{members}]\n", text, count=1)
    if count != 1:
        print("could not find the workspace member list", file=sys.stderr)
        return 1

    def rewrite(match: re.Match[str]) -> str:
        key = match.group("key")
        fields = parse_inline_table(match.group("value"))
        package = fields.get("package", '"' + key + '"').strip('"')

        if key in rewire:
            target = rewire[key]
            fields.pop("path", None)
            for source_field in ("git", "rev", "branch"):
                fields.pop(source_field, None)
            for target_field in ("version", "package", "git", "rev"):
                if target_field in target:
                    fields[target_field] = f'"{target[target_field]}"'
        elif "path" in fields:
            if package in vendored:
                crate = vendored[package]
                fields["path"] = f'"{vendored_directory}/{package}"'
                fields["package"] = f'"{crate.get("package", package)}"'
                fields["version"] = f'"{crate["version"]}"'
            else:
                fields.pop("path")
        elif key not in versions:
            return match.group(0)

        if key in versions:
            fields["version"] = f'"{versions[key]}"'

        return f"{key} = {render(fields)}"

    heading = "[workspace.dependencies]"
    start = text.index(heading)
    end = text.find("\n[", start + len(heading))
    end = len(text) if end == -1 else end
    section = text[start:end]
    for key in unused:
        section, removed = re.subn(
            rf"^{re.escape(key)} = [^\n]*\n", "", section, count=1, flags=re.MULTILINE
        )
        if removed != 1:
            print(f"unused dependency {key} is not in the workspace", file=sys.stderr)
            return 1
    text = text[:start] + DEPENDENCY.sub(rewrite, section) + text[end:]

    patches = manifest.get("patch")
    if patches:
        if re.search(r"^\[patch\.", text, re.MULTILINE):
            print("the upstream manifest already has [patch] tables", file=sys.stderr)
            return 1
        text = text.rstrip("\n") + "\n\n" + render_patches(patches)

    (repo_root / "Cargo.toml").write_text(BANNER + "\n" + text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
